#!/usr/bin/python

from wfrp import *
from commandexecutor import *
import sys

command_executor = CommandExecutor(Wfrp.load())
command_executor.save_after_successful_command = True

try:
    command_executor.execute_command(sys.argv[1:])
    sys.exit(0)
except ValueError as e:
    print(e)
    sys.exit(1)
